# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: false

env:
  global:
    - TENSORFLOW_TEST_EXAMPLES="1"

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "TensorFlow (Stable)"
      env: TENSORFLOW_VERSION="default"
    - name: "TensorFlow Eager (Stable)"
      env:
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (2.0.0)"
      env:
        - TENSORFLOW_VERSION="2.0.0"
        - TENSORFLOW_TEST_EXAMPLES=""
    - name: "TensorFlow (1.14)"
      env:
        - TENSORFLOW_VERSION="1.14"
        - TENSORFLOW_TEST_EXAMPLES=""
    - name: "TensorFlow (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "TensorFlow Eager (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (release version) with reticulate master"
      env:
        - TENSORFLOW_VERSION="1.14"
        - TENSORFLOW_TEST_EXAMPLES=""
      r_github_packages:
        - rstudio/reticulate
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate
  allow_failures:
    - name: "TensorFlow (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "TensorFlow Eager (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
    - name: "TensorFlow (nightly) with reticulate master"
      env:
        - TENSORFLOW_VERSION="nightly"
      r_github_packages:
        - rstudio/reticulate

addons:
  apt:
    packages:
      python3-dev
      python3-pip
      python3-virtualenv
      python3-venv

before_script:
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"), extra_packages="IPython")'
  - R -e 'tensorflow::tf_config()'
